"""
examples/verify_with_verilator.py
==================================
Verify that the Verilog generated by ``circuit.get_verilog_code()`` produces
identical outputs to the Python circuit for a set of random boolean inputs.

Uses Verilator (https://www.veripool.org/verilator/) as the simulation backend.

Requirements
------------
Install verilator before running:

    macOS:   brew install verilator
    Ubuntu:  sudo apt install verilator

Usage
-----
    python examples/verify_with_verilator.py
"""

import pathlib
import shutil
import subprocess
import sys
import tempfile
import textwrap

import numpy as np
import torch
import torch.nn as nn

from torchlogix import Circuit
from torchlogix.layers import LogicDense
from torchlogix.utils import set_export_mode


def _require_verilator():
    if shutil.which("verilator") is None:
        print("verilator not found on PATH — skipping Verilog simulation.")
        print("Install: brew install verilator  (macOS)")
        print("         sudo apt install verilator  (Ubuntu/Debian)")
        sys.exit(0)


def build_circuit() -> Circuit:
    """Build a tiny two-layer boolean circuit (8 inputs → 4 outputs)."""
    torch.manual_seed(0)
    model = nn.Sequential(
        LogicDense(8, 16, parametrization="raw",
                   parametrization_kwargs={"weight_init": "random"}),
        LogicDense(16, 4, parametrization="raw",
                   parametrization_kwargs={"weight_init": "random"}),
    )
    set_export_mode(model)
    circuit = Circuit.from_model(model, input_shape=(8,))
    circuit.simplify()
    return circuit


def _pack_bits(arr: np.ndarray) -> list[int]:
    """Pack each row of a bool array (N, k) into a list of N uint8 values."""
    result = np.zeros(len(arr), dtype=np.uint8)
    for j in range(arr.shape[1]):
        result |= arr[:, j].astype(np.uint8) << j
    return result.tolist()


def make_testbench(n_tests: int, inputs_packed: list[int], expected_packed: list[int]) -> str:
    """Return a Verilator C++ testbench with inlined test vectors."""
    inp_str = ", ".join(str(v) for v in inputs_packed)
    exp_str = ", ".join(str(v) for v in expected_packed)
    return textwrap.dedent(f"""\
        #include "Vcircuit.h"
        #include "verilated.h"
        #include <cstdio>
        #include <cstdint>

        static const uint8_t test_inputs[{n_tests}]    = {{ {inp_str} }};
        static const uint8_t test_expected[{n_tests}]  = {{ {exp_str} }};

        int main(int argc, char** argv) {{
            Verilated::commandArgs(argc, argv);
            Vcircuit dut;
            int failures = 0;
            for (int i = 0; i < {n_tests}; i++) {{
                dut.inp = test_inputs[i];
                dut.eval();
                uint8_t got = dut.out & 0x0F;
                if (got != test_expected[i]) {{
                    failures++;
                    printf("FAIL[%d] inp=0x%02x expected=0x%02x got=0x%02x\\n",
                           i, test_inputs[i], test_expected[i], got);
                }}
            }}
            if (failures == 0)
                printf("PASS: all {n_tests} tests match\\n");
            else
                printf("FAIL: %d/{n_tests} tests failed\\n", failures);
            return failures;
        }}
        """)


def main():
    _require_verilator()

    # 1. Build circuit
    print("Building circuit...")
    circuit = build_circuit()
    print(f"  {circuit}")

    # 2. Random test inputs + expected outputs from Python circuit
    N = 64
    rng = np.random.default_rng(42)
    x_np = rng.integers(0, 2, size=(N, 8)).astype(np.bool_)
    py_out = circuit(torch.from_numpy(x_np)).numpy()  # (N, 4) bool

    # 3. Pack rows to bytes
    inputs_packed   = _pack_bits(x_np)
    expected_packed = _pack_bits(py_out)

    # 4. Generate Verilog
    print("Generating Verilog...")
    verilog = circuit.get_verilog_code()

    # 5. Simulate with verilator in a temp directory
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = pathlib.Path(tmpdir)
        (tmp / "circuit.v").write_text(verilog)
        (tmp / "tb.cpp").write_text(make_testbench(N, inputs_packed, expected_packed))

        print("Running Verilator simulation...")
        build = subprocess.run(
            ["verilator", "--cc", "circuit.v", "--exe", "tb.cpp",
             "--build", "--Mdir", "obj_dir", "-Wno-fatal"],
            cwd=tmpdir, capture_output=True, text=True,
        )
        if build.returncode != 0:
            print("Verilator build failed:")
            print(build.stderr)
            sys.exit(1)

        result = subprocess.run(
            ["./obj_dir/Vcircuit"],
            cwd=tmpdir, capture_output=True, text=True,
        )

    print(result.stdout.strip())
    if result.returncode != 0:
        print(result.stderr.strip())
        sys.exit(1)


if __name__ == "__main__":
    main()
