module logic_net (
    input wire [7:0] inp,
    output wire [1:0] out
);

// Generated by TorchLogix
// Input size: 8 bits
// Output size: 2 bits

    wire [3:0] layer_0_out;


// Layer 0: LogicDense (4 neurons)
    assign layer_0_out[0] = inp[0];
    assign layer_0_out[1] = inp[6];
    assign layer_0_out[2] = inp[3];
    assign layer_0_out[3] = inp[7];

// Layer 1: LogicDense (2 neurons)
    assign out[0] = 1'b1;
    assign out[1] = 1'b0;

endmodule
