on: [push]
jobs:
    Unit-Tests:
        runs-on: ubuntu-latest

        env:
          DIFFLOGIC_BUILD_CUDA_EXT: false

        steps:
            - name: Print job info
              run: |
                echo "This job was automatically triggered by a ${{ github.event_name }} event. It is now running on a ${{ runner.os }} server hosted by GitHub! The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
                echo Running python version `python -V`

            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3

            - name: Install this package
              run: |
                  pip install --upgrade pip
                  pip install ".[dev]"

            - name: Run the unit tests
              run: pytest -s
