module conv_logic_net (
    input wire [63:0] inp,
    output wire [3:0] out
);

// Generated by TorchLogix
// Input size: 64 bits
// Output size: 4 bits

    wire [17:0] layer_0_out;
    wire [17:0] layer_1_out;


// Layer 0: LogicConv (tree_depth=2)
    wire conv_l0_k0_p0_lv0_g0;
    wire conv_l0_k0_p0_lv0_g1;
    wire conv_l0_k0_p0_lv0_g2;
    wire conv_l0_k0_p0_lv0_g3;
    wire conv_l0_k0_p0_lv1_g0;
    wire conv_l0_k0_p0_lv1_g1;
    wire conv_l0_k0_p1_lv0_g0;
    wire conv_l0_k0_p1_lv0_g1;
    wire conv_l0_k0_p1_lv0_g2;
    wire conv_l0_k0_p1_lv0_g3;
    wire conv_l0_k0_p1_lv1_g0;
    wire conv_l0_k0_p1_lv1_g1;
    wire conv_l0_k0_p2_lv0_g0;
    wire conv_l0_k0_p2_lv0_g1;
    wire conv_l0_k0_p2_lv0_g2;
    wire conv_l0_k0_p2_lv0_g3;
    wire conv_l0_k0_p2_lv1_g0;
    wire conv_l0_k0_p2_lv1_g1;
    wire conv_l0_k0_p3_lv0_g0;
    wire conv_l0_k0_p3_lv0_g1;
    wire conv_l0_k0_p3_lv0_g2;
    wire conv_l0_k0_p3_lv0_g3;
    wire conv_l0_k0_p3_lv1_g0;
    wire conv_l0_k0_p3_lv1_g1;
    wire conv_l0_k0_p4_lv0_g0;
    wire conv_l0_k0_p4_lv0_g1;
    wire conv_l0_k0_p4_lv0_g2;
    wire conv_l0_k0_p4_lv0_g3;
    wire conv_l0_k0_p4_lv1_g0;
    wire conv_l0_k0_p4_lv1_g1;
    wire conv_l0_k0_p5_lv0_g0;
    wire conv_l0_k0_p5_lv0_g1;
    wire conv_l0_k0_p5_lv0_g2;
    wire conv_l0_k0_p5_lv0_g3;
    wire conv_l0_k0_p5_lv1_g0;
    wire conv_l0_k0_p5_lv1_g1;
    wire conv_l0_k0_p6_lv0_g0;
    wire conv_l0_k0_p6_lv0_g1;
    wire conv_l0_k0_p6_lv0_g2;
    wire conv_l0_k0_p6_lv0_g3;
    wire conv_l0_k0_p6_lv1_g0;
    wire conv_l0_k0_p6_lv1_g1;
    wire conv_l0_k0_p7_lv0_g0;
    wire conv_l0_k0_p7_lv0_g1;
    wire conv_l0_k0_p7_lv0_g2;
    wire conv_l0_k0_p7_lv0_g3;
    wire conv_l0_k0_p7_lv1_g0;
    wire conv_l0_k0_p7_lv1_g1;
    wire conv_l0_k0_p8_lv0_g0;
    wire conv_l0_k0_p8_lv0_g1;
    wire conv_l0_k0_p8_lv0_g2;
    wire conv_l0_k0_p8_lv0_g3;
    wire conv_l0_k0_p8_lv1_g0;
    wire conv_l0_k0_p8_lv1_g1;
    wire conv_l0_k1_p0_lv0_g0;
    wire conv_l0_k1_p0_lv0_g1;
    wire conv_l0_k1_p0_lv0_g2;
    wire conv_l0_k1_p0_lv0_g3;
    wire conv_l0_k1_p0_lv1_g0;
    wire conv_l0_k1_p0_lv1_g1;
    wire conv_l0_k1_p1_lv0_g0;
    wire conv_l0_k1_p1_lv0_g1;
    wire conv_l0_k1_p1_lv0_g2;
    wire conv_l0_k1_p1_lv0_g3;
    wire conv_l0_k1_p1_lv1_g0;
    wire conv_l0_k1_p1_lv1_g1;
    wire conv_l0_k1_p2_lv0_g0;
    wire conv_l0_k1_p2_lv0_g1;
    wire conv_l0_k1_p2_lv0_g2;
    wire conv_l0_k1_p2_lv0_g3;
    wire conv_l0_k1_p2_lv1_g0;
    wire conv_l0_k1_p2_lv1_g1;
    wire conv_l0_k1_p3_lv0_g0;
    wire conv_l0_k1_p3_lv0_g1;
    wire conv_l0_k1_p3_lv0_g2;
    wire conv_l0_k1_p3_lv0_g3;
    wire conv_l0_k1_p3_lv1_g0;
    wire conv_l0_k1_p3_lv1_g1;
    wire conv_l0_k1_p4_lv0_g0;
    wire conv_l0_k1_p4_lv0_g1;
    wire conv_l0_k1_p4_lv0_g2;
    wire conv_l0_k1_p4_lv0_g3;
    wire conv_l0_k1_p4_lv1_g0;
    wire conv_l0_k1_p4_lv1_g1;
    wire conv_l0_k1_p5_lv0_g0;
    wire conv_l0_k1_p5_lv0_g1;
    wire conv_l0_k1_p5_lv0_g2;
    wire conv_l0_k1_p5_lv0_g3;
    wire conv_l0_k1_p5_lv1_g0;
    wire conv_l0_k1_p5_lv1_g1;
    wire conv_l0_k1_p6_lv0_g0;
    wire conv_l0_k1_p6_lv0_g1;
    wire conv_l0_k1_p6_lv0_g2;
    wire conv_l0_k1_p6_lv0_g3;
    wire conv_l0_k1_p6_lv1_g0;
    wire conv_l0_k1_p6_lv1_g1;
    wire conv_l0_k1_p7_lv0_g0;
    wire conv_l0_k1_p7_lv0_g1;
    wire conv_l0_k1_p7_lv0_g2;
    wire conv_l0_k1_p7_lv0_g3;
    wire conv_l0_k1_p7_lv1_g0;
    wire conv_l0_k1_p7_lv1_g1;
    wire conv_l0_k1_p8_lv0_g0;
    wire conv_l0_k1_p8_lv0_g1;
    wire conv_l0_k1_p8_lv0_g2;
    wire conv_l0_k1_p8_lv0_g3;
    wire conv_l0_k1_p8_lv1_g0;
    wire conv_l0_k1_p8_lv1_g1;

// Kernel 0, Position 0
    assign conv_l0_k0_p0_lv0_g0 = inp[16];
    assign conv_l0_k0_p0_lv0_g1 = inp[0];
    assign conv_l0_k0_p0_lv0_g2 = inp[16];
    assign conv_l0_k0_p0_lv0_g3 = inp[17];
    assign conv_l0_k0_p0_lv1_g0 = conv_l0_k0_p0_lv0_g0;
    assign conv_l0_k0_p0_lv1_g1 = conv_l0_k0_p0_lv0_g2;
    assign layer_0_out[0] = conv_l0_k0_p0_lv1_g0;

// Kernel 0, Position 1
    assign conv_l0_k0_p1_lv0_g0 = inp[18];
    assign conv_l0_k0_p1_lv0_g1 = inp[2];
    assign conv_l0_k0_p1_lv0_g2 = inp[18];
    assign conv_l0_k0_p1_lv0_g3 = inp[19];
    assign conv_l0_k0_p1_lv1_g0 = conv_l0_k0_p1_lv0_g0;
    assign conv_l0_k0_p1_lv1_g1 = conv_l0_k0_p1_lv0_g2;
    assign layer_0_out[1] = conv_l0_k0_p1_lv1_g0;

// Kernel 0, Position 2
    assign conv_l0_k0_p2_lv0_g0 = inp[20];
    assign conv_l0_k0_p2_lv0_g1 = inp[4];
    assign conv_l0_k0_p2_lv0_g2 = inp[20];
    assign conv_l0_k0_p2_lv0_g3 = inp[21];
    assign conv_l0_k0_p2_lv1_g0 = conv_l0_k0_p2_lv0_g0;
    assign conv_l0_k0_p2_lv1_g1 = conv_l0_k0_p2_lv0_g2;
    assign layer_0_out[2] = conv_l0_k0_p2_lv1_g0;

// Kernel 0, Position 3
    assign conv_l0_k0_p3_lv0_g0 = inp[32];
    assign conv_l0_k0_p3_lv0_g1 = inp[16];
    assign conv_l0_k0_p3_lv0_g2 = inp[32];
    assign conv_l0_k0_p3_lv0_g3 = inp[33];
    assign conv_l0_k0_p3_lv1_g0 = conv_l0_k0_p3_lv0_g0;
    assign conv_l0_k0_p3_lv1_g1 = conv_l0_k0_p3_lv0_g2;
    assign layer_0_out[3] = conv_l0_k0_p3_lv1_g0;

// Kernel 0, Position 4
    assign conv_l0_k0_p4_lv0_g0 = inp[34];
    assign conv_l0_k0_p4_lv0_g1 = inp[18];
    assign conv_l0_k0_p4_lv0_g2 = inp[34];
    assign conv_l0_k0_p4_lv0_g3 = inp[35];
    assign conv_l0_k0_p4_lv1_g0 = conv_l0_k0_p4_lv0_g0;
    assign conv_l0_k0_p4_lv1_g1 = conv_l0_k0_p4_lv0_g2;
    assign layer_0_out[4] = conv_l0_k0_p4_lv1_g0;

// Kernel 0, Position 5
    assign conv_l0_k0_p5_lv0_g0 = inp[36];
    assign conv_l0_k0_p5_lv0_g1 = inp[20];
    assign conv_l0_k0_p5_lv0_g2 = inp[36];
    assign conv_l0_k0_p5_lv0_g3 = inp[37];
    assign conv_l0_k0_p5_lv1_g0 = conv_l0_k0_p5_lv0_g0;
    assign conv_l0_k0_p5_lv1_g1 = conv_l0_k0_p5_lv0_g2;
    assign layer_0_out[5] = conv_l0_k0_p5_lv1_g0;

// Kernel 0, Position 6
    assign conv_l0_k0_p6_lv0_g0 = inp[48];
    assign conv_l0_k0_p6_lv0_g1 = inp[32];
    assign conv_l0_k0_p6_lv0_g2 = inp[48];
    assign conv_l0_k0_p6_lv0_g3 = inp[49];
    assign conv_l0_k0_p6_lv1_g0 = conv_l0_k0_p6_lv0_g0;
    assign conv_l0_k0_p6_lv1_g1 = conv_l0_k0_p6_lv0_g2;
    assign layer_0_out[6] = conv_l0_k0_p6_lv1_g0;

// Kernel 0, Position 7
    assign conv_l0_k0_p7_lv0_g0 = inp[50];
    assign conv_l0_k0_p7_lv0_g1 = inp[34];
    assign conv_l0_k0_p7_lv0_g2 = inp[50];
    assign conv_l0_k0_p7_lv0_g3 = inp[51];
    assign conv_l0_k0_p7_lv1_g0 = conv_l0_k0_p7_lv0_g0;
    assign conv_l0_k0_p7_lv1_g1 = conv_l0_k0_p7_lv0_g2;
    assign layer_0_out[7] = conv_l0_k0_p7_lv1_g0;

// Kernel 0, Position 8
    assign conv_l0_k0_p8_lv0_g0 = inp[52];
    assign conv_l0_k0_p8_lv0_g1 = inp[36];
    assign conv_l0_k0_p8_lv0_g2 = inp[52];
    assign conv_l0_k0_p8_lv0_g3 = inp[53];
    assign conv_l0_k0_p8_lv1_g0 = conv_l0_k0_p8_lv0_g0;
    assign conv_l0_k0_p8_lv1_g1 = conv_l0_k0_p8_lv0_g2;
    assign layer_0_out[8] = conv_l0_k0_p8_lv1_g0;

// Kernel 1, Position 0
    assign conv_l0_k1_p0_lv0_g0 = inp[0];
    assign conv_l0_k1_p0_lv0_g1 = inp[9];
    assign conv_l0_k1_p0_lv0_g2 = inp[0];
    assign conv_l0_k1_p0_lv0_g3 = inp[18];
    assign conv_l0_k1_p0_lv1_g0 = conv_l0_k1_p0_lv0_g0;
    assign conv_l0_k1_p0_lv1_g1 = conv_l0_k1_p0_lv0_g2;
    assign layer_0_out[9] = conv_l0_k1_p0_lv1_g0;

// Kernel 1, Position 1
    assign conv_l0_k1_p1_lv0_g0 = inp[2];
    assign conv_l0_k1_p1_lv0_g1 = inp[11];
    assign conv_l0_k1_p1_lv0_g2 = inp[2];
    assign conv_l0_k1_p1_lv0_g3 = inp[20];
    assign conv_l0_k1_p1_lv1_g0 = conv_l0_k1_p1_lv0_g0;
    assign conv_l0_k1_p1_lv1_g1 = conv_l0_k1_p1_lv0_g2;
    assign layer_0_out[10] = conv_l0_k1_p1_lv1_g0;

// Kernel 1, Position 2
    assign conv_l0_k1_p2_lv0_g0 = inp[4];
    assign conv_l0_k1_p2_lv0_g1 = inp[13];
    assign conv_l0_k1_p2_lv0_g2 = inp[4];
    assign conv_l0_k1_p2_lv0_g3 = inp[22];
    assign conv_l0_k1_p2_lv1_g0 = conv_l0_k1_p2_lv0_g0;
    assign conv_l0_k1_p2_lv1_g1 = conv_l0_k1_p2_lv0_g2;
    assign layer_0_out[11] = conv_l0_k1_p2_lv1_g0;

// Kernel 1, Position 3
    assign conv_l0_k1_p3_lv0_g0 = inp[16];
    assign conv_l0_k1_p3_lv0_g1 = inp[25];
    assign conv_l0_k1_p3_lv0_g2 = inp[16];
    assign conv_l0_k1_p3_lv0_g3 = inp[34];
    assign conv_l0_k1_p3_lv1_g0 = conv_l0_k1_p3_lv0_g0;
    assign conv_l0_k1_p3_lv1_g1 = conv_l0_k1_p3_lv0_g2;
    assign layer_0_out[12] = conv_l0_k1_p3_lv1_g0;

// Kernel 1, Position 4
    assign conv_l0_k1_p4_lv0_g0 = inp[18];
    assign conv_l0_k1_p4_lv0_g1 = inp[27];
    assign conv_l0_k1_p4_lv0_g2 = inp[18];
    assign conv_l0_k1_p4_lv0_g3 = inp[36];
    assign conv_l0_k1_p4_lv1_g0 = conv_l0_k1_p4_lv0_g0;
    assign conv_l0_k1_p4_lv1_g1 = conv_l0_k1_p4_lv0_g2;
    assign layer_0_out[13] = conv_l0_k1_p4_lv1_g0;

// Kernel 1, Position 5
    assign conv_l0_k1_p5_lv0_g0 = inp[20];
    assign conv_l0_k1_p5_lv0_g1 = inp[29];
    assign conv_l0_k1_p5_lv0_g2 = inp[20];
    assign conv_l0_k1_p5_lv0_g3 = inp[38];
    assign conv_l0_k1_p5_lv1_g0 = conv_l0_k1_p5_lv0_g0;
    assign conv_l0_k1_p5_lv1_g1 = conv_l0_k1_p5_lv0_g2;
    assign layer_0_out[14] = conv_l0_k1_p5_lv1_g0;

// Kernel 1, Position 6
    assign conv_l0_k1_p6_lv0_g0 = inp[32];
    assign conv_l0_k1_p6_lv0_g1 = inp[41];
    assign conv_l0_k1_p6_lv0_g2 = inp[32];
    assign conv_l0_k1_p6_lv0_g3 = inp[50];
    assign conv_l0_k1_p6_lv1_g0 = conv_l0_k1_p6_lv0_g0;
    assign conv_l0_k1_p6_lv1_g1 = conv_l0_k1_p6_lv0_g2;
    assign layer_0_out[15] = conv_l0_k1_p6_lv1_g0;

// Kernel 1, Position 7
    assign conv_l0_k1_p7_lv0_g0 = inp[34];
    assign conv_l0_k1_p7_lv0_g1 = inp[43];
    assign conv_l0_k1_p7_lv0_g2 = inp[34];
    assign conv_l0_k1_p7_lv0_g3 = inp[52];
    assign conv_l0_k1_p7_lv1_g0 = conv_l0_k1_p7_lv0_g0;
    assign conv_l0_k1_p7_lv1_g1 = conv_l0_k1_p7_lv0_g2;
    assign layer_0_out[16] = conv_l0_k1_p7_lv1_g0;

// Kernel 1, Position 8
    assign conv_l0_k1_p8_lv0_g0 = inp[36];
    assign conv_l0_k1_p8_lv0_g1 = inp[45];
    assign conv_l0_k1_p8_lv0_g2 = inp[36];
    assign conv_l0_k1_p8_lv0_g3 = inp[54];
    assign conv_l0_k1_p8_lv1_g0 = conv_l0_k1_p8_lv0_g0;
    assign conv_l0_k1_p8_lv1_g1 = conv_l0_k1_p8_lv0_g2;
    assign layer_0_out[17] = conv_l0_k1_p8_lv1_g0;

// Layer 1: Flatten
    assign layer_1_out = layer_0_out;

// Layer 2: LogicDense (4 neurons)
    assign out[0] = layer_1_out[13];
    assign out[1] = layer_1_out[12];
    assign out[2] = layer_1_out[11];
    assign out[3] = layer_1_out[10];

endmodule
